import { v4 as uuidv4 } from "uuid";

export const data = [
  {
    id: "12",
    name: "Georges Carlton",
    src: "/images/man.png",
    alt: "man",
    likes: 12,
    likeBool: false,
    description: "Designer from Denver",
    category: "designer",
    title: "My own design",
    portfolio: [
      { src: "/images/design.jpg", alt: "design" },
      { src: "/images/design2.jpg", alt: "design" },
      { src: "/images/design3.jpg", alt: "design" },
      { src: "/images/design4.jpg", alt: "design" },
      { src: "/images/design5.jpg", alt: "design" },
      { src: "/images/design6.jpg", alt: "design" },
      { src: "/images/design7.jpeg", alt: "design" },
    ],
  },
  {
    id: "123",
    name: "Catarina Pavlov",
    src: "/images/woman1.jpg",
    alt: "woman",
    likes: 120,
    likeBool: false,
    description: "Photographer from Bratislava",
    category: "photographer",
    title: "Photos from klapovic Park",
    portfolio: [
      { src: "/images/photo.jpg", alt: "photo" },
      { src: "/images/photo2.jpg", alt: "photo" },
      { src: "/images/photo3.jpg", alt: "photo" },
      { src: "/images/photo4.jpeg", alt: "photo" },
      { src: "/images/photo5.jpg", alt: "photo" },
      { src: "/images/photo6.jpg", alt: "photo" },
      { src: "/images/photo7.jpg", alt: "photo" },
    ],
  },
  {
    id: "11",
    name: "Clara carmin",
    src: "/images/woman2.jpg",
    alt: "woman",
    likes: 8,
    likeBool: false,
    description: "Photographer from Bratislava",
    category: "photographer",
    title: "Photos from klapovic Park",
    portfolio: [
      { src: "/images/photo.jpg", alt: "photo" },
      { src: "/images/photo2.jpg", alt: "photo" },
      { src: "/images/photo3.jpg", alt: "photo" },
      { src: "/images/photo4.jpeg", alt: "photo" },
      { src: "/images/photo5.jpg", alt: "photo" },
      { src: "/images/photo6.jpg", alt: "photo" },
      { src: "/images/photo7.jpg", alt: "photo" },
    ],
  },
  {
    id: "15",
    name: "Rémi Castor",
    src: "/images/man2.jpg",
    alt: "man",
    likes: 12,
    likeBool: false,
    description: "Photographer from Karthoum",
    category: "photographer",
    title: "Photos from Kharthoum Park",
    portfolio: [
      { src: "/images/photo.jpg", alt: "photo" },
      { src: "/images/photo2.jpg", alt: "photo" },
      { src: "/images/photo3.jpg", alt: "photo" },
      { src: "/images/photo4.jpeg", alt: "photo" },
      { src: "/images/photo5.jpg", alt: "photo" },
      { src: "/images/photo6.jpg", alt: "photo" },
      { src: "/images/photo7.jpg", alt: "photo" },
    ],
  },
  {
    id: "25",
    name: "Gaspard Chalamet",
    src: "/images/man3.jpg",
    alt: "man",
    likes: 103,
    likeBool: false,
    description: "Designer from Berlin",
    category: "designer",
    title: "design from my imagination",
    portfolio: [
      { src: "/images/design.jpg", alt: "design" },
      { src: "/images/design2.jpg", alt: "design" },
      { src: "/images/design3.jpg", alt: "design" },
      { src: "/images/design4.jpg", alt: "design" },
      { src: "/images/design5.jpg", alt: "design" },
      { src: "/images/design6.jpg", alt: "design" },
      { src: "/images/design7.jpeg", alt: "design" },
    ],
  },
  {
    id: "45",
    name: "Amélie Partouche",
    src: "/images/woman3.jpg",
    alt: "woman",
    likes: 99,
    likeBool: false,
    description: "Designer from Cagliari",
    category: "designer",
    title: "design from my imagination",
    portfolio: [
      { src: "/images/design.jpg", alt: "design" },
      { src: "/images/design2.jpg", alt: "design" },
      { src: "/images/design3.jpg", alt: "design" },
      { src: "/images/design4.jpg", alt: "design" },
      { src: "/images/design5.jpg", alt: "design" },
      { src: "/images/design6.jpg", alt: "design" },
      { src: "/images/design7.jpeg", alt: "design" },
    ],
  },
  {
    id: "122133",
    name: "Peter Balls",
    src: "/images/man.png",
    alt: "man",
    likes: 12,
    likeBool: false,
    description: "Designer from Denver",
    category: "designer",
    title: "My own design",
    portfolio: [
      { src: "/images/design.jpg", alt: "design" },
      { src: "/images/design2.jpg", alt: "design" },
      { src: "/images/design3.jpg", alt: "design" },
      { src: "/images/design4.jpg", alt: "design" },
      { src: "/images/design5.jpg", alt: "design" },
      { src: "/images/design6.jpg", alt: "design" },
      { src: "/images/design7.jpeg", alt: "design" },
    ],
  },
  {
    id: "18993",
    name: "Christine Jalie",
    src: "/images/woman1.jpg",
    alt: "woman",
    likes: 120,
    likeBool: false,
    description: "Photographer from Bratislava",
    category: "photographer",
    title: "Photos from klapovic Park",
    portfolio: [
      { src: "/images/photo.jpg", alt: "photo" },
      { src: "/images/photo2.jpg", alt: "photo" },
      { src: "/images/photo3.jpg", alt: "photo" },
      { src: "/images/photo4.jpeg", alt: "photo" },
      { src: "/images/photo5.jpg", alt: "photo" },
      { src: "/images/photo6.jpg", alt: "photo" },
      { src: "/images/photo7.jpg", alt: "photo" },
    ],
  },
  {
    id: "5645616",
    name: "Cunigonde Bächen",
    src: "/images/woman2.jpg",
    alt: "woman",
    likes: 8,
    likeBool: false,
    description: "Photographer from Bratislava",
    category: "photographer",
    title: "Photos from klapovic Park",
    portfolio: [
      { src: "/images/photo.jpg", alt: "photo" },
      { src: "/images/photo2.jpg", alt: "photo" },
      { src: "/images/photo3.jpg", alt: "photo" },
      { src: "/images/photo4.jpeg", alt: "photo" },
      { src: "/images/photo5.jpg", alt: "photo" },
      { src: "/images/photo6.jpg", alt: "photo" },
      { src: "/images/photo7.jpg", alt: "photo" },
    ],
  },
  {
    id: "14555",
    name: "Silvio Romanella",
    src: "/images/man2.jpg",
    alt: "man",
    likes: 12,
    likeBool: false,
    description: "Photographer from Karthoum",
    category: "photographer",
    title: "Photos from Kharthoum Park",
    portfolio: [
      { src: "/images/photo.jpg", alt: "photo" },
      { src: "/images/photo2.jpg", alt: "photo" },
      { src: "/images/photo3.jpg", alt: "photo" },
      { src: "/images/photo4.jpeg", alt: "photo" },
      { src: "/images/photo5.jpg", alt: "photo" },
      { src: "/images/photo6.jpg", alt: "photo" },
      { src: "/images/photo7.jpg", alt: "photo" },
    ],
  },
  {
    id: "251254",
    name: "Carmin Smith",
    src: "/images/man3.jpg",
    alt: "man",
    likes: 103,
    likeBool: false,
    description: "Designer from Berlin",
    category: "designer",
    title: "design from my imagination",
    portfolio: [
      { src: "/images/design.jpg", alt: "design" },
      { src: "/images/design2.jpg", alt: "design" },
      { src: "/images/design3.jpg", alt: "design" },
      { src: "/images/design4.jpg", alt: "design" },
      { src: "/images/design5.jpg", alt: "design" },
      { src: "/images/design6.jpg", alt: "design" },
      { src: "/images/design7.jpeg", alt: "design" },
    ],
  },
  {
    id: "455464532",
    name: "Saoirse Ronan",
    src: "/images/woman3.jpg",
    alt: "woman",
    likes: 99,
    likeBool: false,
    description: "Designer from Cagliari",
    category: "designer",
    title: "design from my imagination",
    portfolio: [
      { src: "/images/design.jpg", alt: "design" },
      { src: "/images/design2.jpg", alt: "design" },
      { src: "/images/design3.jpg", alt: "design" },
      { src: "/images/design4.jpg", alt: "design" },
      { src: "/images/design5.jpg", alt: "design" },
      { src: "/images/design6.jpg", alt: "design" },
      { src: "/images/design7.jpeg", alt: "design" },
    ],
  },
];
